version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck: # Health check for PostgreSQL
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./ # Ensure the build context is correct
    depends_on:
      - db # Start after PostgreSQL
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    ports:
      - '8000:8000'

volumes:
  postgres_data: # Define the referenced volume
    name: postgres_data # Optional: Explicitly name the volume
